#!/bin/bash

set -e

if [ "$PHP_VERSION" == "" ]; then
  echo "must set PHP_VERSION, i.e PHP_VERSION=5.4.1"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID, i.e. export AWS_ID=1BHAJK48DJFMQKZMNV93"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET, i.e. export AWS_SECRET=fj2jjchebsjksmMJCN387RHNjdnddNfi4jjhshh3"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET, i.e. S3_BUCKET=heroku-buildpack-wordpress"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t php_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract nginx
curl -L http://us.php.net/get/php-$PHP_VERSION.tar.bz2/from/www.php.net/mirror -o - | tar xj

# build and package nginx for heroku
vulcan build -v -s php-$PHP_VERSION -o $tempdir/php-$PHP_VERSION-with-fpm-heroku.tar.gz -p /app/vendor/php -c '\
	./configure \
	--prefix=/app/vendor/php \
	--with-config-file-path=/app/vendor/php \
	--with-config-file-scan-dir=/app/vendor/php/etc.d \
	--enable-static \
	--disable-shared \
	--disable-debug \
	--disable-rpath \
	--enable-fpm \
	--enable-gd-native-ttf \
	--enable-inline-optimization \
	--enable-libxml \
	--enable-mbregex \
	--enable-mbstring \
	--enable-pcntl \
	--enable-soap=shared \
	--enable-zip \
	--with-bz2 \
	--with-curl \
	--with-gd \
	--with-gettext \
	--with-jpeg-dir \
	--with-mcrypt=#{dir}/deps \
	--with-iconv \
	--with-mhash \
	--with-mysql \
	--with-mysqli \
	--with-openssl \
	--with-pcre-regex \
	--with-pdo-mysql \
	--with-png-dir \
	--with-zlib \
	--without-pdo-sqlite \
	--without-sqlite3' -d https://s3.amazonaws.com/$S3_BUCKET/libmcrypt-$LIBMCRYPT_VERSION.tar.gz

popd

cp $tempdir/php-$PHP_VERSION-with-fpm-heroku.tar.gz .

echo "+ Binaries available at ./php-$PHP_VERSION-with-fpm-heroku.tar.gz"
echo "+ Upload this package to Amazon S3."

# upload to s3
#$basedir/aws/s3 put $S3_BUCKET php-$PHP_VERSION-with-fpm-heroku.tar.gz $tempdir/php-$PHP_VERSION-with-fpm-heroku.tar.gz
#s3cmd put $tempdir/php-$PHP_VERSION-with-fpm-heroku.tar.gz s3://$S3_BUCKET
