require_relative "spec_helper"

describe "A PHP application intended for Composer 1", :stack => "heroku-20" do
	context "with a composer.lock generated by an old version of Composer" do
		it "builds using Composer 1.x and prints a notice" do
			new_app_with_stack_and_platrepo('test/fixtures/composer/basic_lock_oldv1').deploy do |app|
				expect(app.output).to match(/No Composer plugin-api-version recorded/)
				expect(app.output).to match(/- composer \(1/)
				expect(app.output).to match(/Composer version 1/)
			end
		end
	end
	context "with a composer.lock generated by a late version 1 of Composer" do
		before(:all) do
			@app = new_app_with_stack_and_platrepo('test/fixtures/composer/basic_lock_v1')
			@app.deploy
		end
		
		after(:all) do
			@app.teardown!
		end
		
		it "builds using Composer 1.x" do
			expect(@app.output).to match(/- composer \(1/)
			expect(@app.output).to match(/Composer version 1/)
		end
		
		context "with a malformed COMPOSER_AUTH env var" do
			it "still boots" do
				# config test is enough, it's past any uses of composer on startup
				cmds = ['heroku-php-apache2', 'heroku-php-nginx'].map { |script| "#{script} -t" }
				retry_until retry: 3, sleep: 5 do
					expect_exit(code: 0) { @app.run("( set -e; #{cmds.join('; ')}; )", :return_obj => true, :heroku => {:env => "COMPOSER_AUTH=malformed"}) }
				end
			end
		end
	end
end
