require_relative "spec_helper"

describe "A PHP application intended for Composer 1" do
	context "with a composer.lock generated by a very old version of Composer 1 (without a platform-api-version entry)" do
		it "rejects the lock file" do
			new_app_with_stack_and_platrepo('test/fixtures/composer/basic_lock_oldv1', allow_failure: true).deploy do |app|
				expect(app.output).to include("ERROR: No Composer plugin-api-version recorded")
				expect(app.output).to include("Please update it using a recent version of Composer")
			end
		end
	end
	context "with a composer.lock generated by a late version 1 of Composer (with a platform-api-version entry)" do
		it "fails to build due to missing Composer 1 support" do
			new_app_with_stack_and_platrepo('test/fixtures/composer/basic_lock_v1', allow_failure: true).deploy do |app|
				expect(app.output).to include("requires composer-plugin-api ^1")
			end
		end
	end
end
