#!/bin/bash

# fail hard
set -o pipefail
# fail harder
set -eux

#
#./configure --prefix=/tmp/foo1
#https://launchpad.net/libmemcached/1.0/1.0.16/+download/libmemcached-1.0.16.tar.gz
#

PREFIX=/app/.heroku/php
mkdir -p $PREFIX

curl -LO ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz
tar xzf cyrus-sasl-2.1.26.tar.gz
pushd cyrus-sasl-2.1.26
./configure --prefix=$PREFIX
make
make install
popd

# Take care of vendoring
dep_version=${VERSION:-1.0.18}
dep_dirname=libmemcached-${dep_version}
dep_archive_name=${dep_dirname}.tar.gz

curl -LO https://launchpad.net/libmemcached/1.0/${dep_version}/+download/${dep_archive_name}

tar xzf $dep_archive_name
pushd $dep_dirname
CPPFLAGS=-I$PREFIX/include LDFLAGS=-L$PREFIX/lib ./configure --prefix=$PREFIX --without-memcached
make
make install
popd

mv $PREFIX/* $2/

echo "Done packaging $dep_dirname"
