#!/bin/bash
# Build Path: /app/.heroku/php/

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eux

# Take care of vendoring
dep_archive_name=zlib-1.2.8.tar.gz

curl -Lo $dep_archive_name http://zlib.net/${dep_archive_name}

tar xzf $dep_archive_name
pushd $dep_dirname
./configure --prefix=$OUT_PREFIX
make
make install
popd

mv $OUT_PREFIX/* $2/

echo "Done packaging $dep_dirname"
