name: Prepare Release

on:
  workflow_dispatch:

# _platform-repo-snapshot-calc needs read access for checkout
# _classic-buildpack-prepare-release uses a GitHub App token instead
permissions:
  contents: read

env:
  # ensure these are in sync with other relevant workflow files
  stacks_list_for_shell_expansion: "{heroku-22,heroku-24-amd64,heroku-24-arm64}"

jobs:
  check-platform-repo-snapshot:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Perform platform repo snapshot checks
        id: platform-repo-snapshot-calc
        uses: ./.github/actions/platform-repo-snapshot-calc
        with:
          stacks-list-for-shell-expansion: ${{env.stacks_list_for_shell_expansion}}
          repo-path-suffix: "-stable/"
      - name: Fail if repo snapshots are missing for any of the stacks
        if: steps.platform-repo-snapshot-calc.outputs.snapshot-urls-check-outcome != 'success'
        run: |
          # snapshot-urls output is not quoted so that the shell expands the brace expression for us
          echo "::error title=Platform repo snapshot(s) missing::One or more of the following URLs were not found:" ${{ steps.platform-repo-snapshot-calc.outputs.snapshot-urls }}
          exit 1
  prepare-release:
    needs: check-platform-repo-snapshot
    uses: heroku/languages-github-actions/.github/workflows/_classic-buildpack-prepare-release.yml@latest
    secrets: inherit
