#!/usr/bin/env bash
# Build Path: /app/.heroku/php/
# Build Deps: libraries/zlib, libraries/libmemcached

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eux

mkdir bin
export PATH=$PWD/bin:$PATH


# Take care of vendoring
dep_version=${VERSION:-5.5.10}
dep_dirname=php-$dep_version
dep_archive_name=$dep_dirname.tar.bz2

# Download PHP source.
curl -Lo $dep_archive_name http://us1.php.net/get/$dep_archive_name/from/www.php.net/mirror

# Fetch mcrypt
if [ -z MCRYPT_URL ]
then
    MCRYPT_URL="https://heroku-buildpack-php.s3.amazonaws.com/mcrypt-2.5.8-2.tar.gz"
fi
#curl --silent --max-time 60 --location "$MCRYPT_URL" | tar xz

# Clean and extract PHP.
rm -rf $dep_dirname
tar jxf $dep_archive_name

# cannot be built shared: date, ereg, opcache (always), pcre, reflection, sockets (?), spl, standard,

# Compile PHP
pushd $dep_dirname
./configure \
    --prefix=$OUT_PREFIX \
    --with-config-file-path=/app/.heroku/php/etc \
    --with-config-file-scan-dir=/app/.heroku/php/etc/php/conf.d \
    --with-openssl \
    --enable-fpm \
    --enable-soap=shared \
    --enable-sockets \
    --enable-zip \
    --with-zlib=$OUT_PREFIX \
    --with-pgsql \
    --with-pdo-pgsql \
    --with-mysql \
    --with-mysqli \
    --with-pdo-mysql
make -s
make install -s
popd

# PHP Memcache Extension
curl -L https://github.com/php-memcached-dev/php-memcached/archive/2.2.0RC1.tar.gz | tar xz
pushd php-memcached-2.2.0RC1
phpize
./configure \
    --enable-memcached \
    --with-libmemcached-dir=$OUT_PREFIX
make -s
make install -s
popd

# Copy in MySQL client library.
# mkdir -p $PREFIX/lib/phpls
# cp /usr/lib/libmysqlclient.so.16 $PREFIX/lib/php

# $PATH manipulation Necessary for 'pecl install', which relies on
# PHP binaries relative to $PATH.

$OUT_PREFIX/bin/pecl channel-update pecl.php.net

# bundle composer
curl -sS https://getcomposer.org/installer | php -- --install-dir=$OUT_PREFIX/bin
mv $OUT_PREFIX/bin/composer.phar $OUT_PREFIX/bin/composer

# Use defaults for apc build prompts.
# yes '' | $OUT_PREFIX/bin/pecl install apc

# echo $dep_version > $OUT_PREFIX/.heroku/dep_version

mv $OUT_PREFIX/* $2/

echo "Done building $dep_dirname"